# [<en>] section for bootstrapping the Deckhouse cluster (InitConfiguration)
# [<en>] version of the Deckhouse API
# [<ru>] секция первичной инициализации кластера Deckhouse (InitConfiguration)
# [<ru>] используемая версия API Deckhouse
apiVersion: deckhouse.io/v1
# [<en>] type of the configuration section
# [<ru>] тип секции конфигурации
kind: InitConfiguration
# [<en>] Deckhouse parameters
# [<ru>] секция с параметрами Deckhouse
deckhouse:
  # [<en>] the release channel in use
  # [<ru>] используемый канал обновлений
  releaseChannel: Stable
  # [<en>] the Managed bundle is used when installing Deckhouse in an existing cluster
  # [<ru>] при установке Deckhouse в существующий кластер используется вариант поставки — Managed
  bundle: Minimal
  configOverrides:
    global:
      modules:
        # [<en>] template that will be used for system apps domains within the cluster
        # [<en>] e.g., Grafana for %s.example.com will be available as grafana.example.com
        # [<ru>] шаблон, который будет использоваться для составления адресов системных приложений в кластере
        # [<ru>] например, Grafana для %s.example.com будет доступна на домене grafana.example.com
        publicDomainTemplate: "%s.example.com"
        # [<en>] if there are no master nodes in the cluster (cloud managed control-plane) or they have special taints
        # [<en>] specify them to allow Deckhouse components to start or delete the `placement` block
        # [<ru>] если в кластере отсутствуют master-узлы (cloud managed control-plane) или у них особые taint
        # [<ru>] укажите их, чтобы позволить запуститься компонентам Deckhouse или удалите блок `placement`
        # [<en>] you might consider changing this
        # [<ru>] возможно, захотите изменить
        placement:
          customTolerationKeys:
          - CriticalAddonsOnly
    certManagerEnabled: true
    deckhouseWebEnabled: true
    operatorPrometheusCrdEnabled: true
    priorityClassEnabled: true
    prometheusCrdEnabled: true
    verticalPodAutoscalerCrdEnabled: true
    userAuthnCrdEnabled: true
    helmEnabled: true
    # [<en>] Enable if you don't have an Ingress controller installed in your cluster yet
    # [<ru>] Включите, если у вас в кластере еще не установлен Ingress-контроллер
    # [<en>] you might consider changing this
    # [<ru>] возможно, захотите изменить
    nginxIngressEnabled: false
    # [<ru>] включите интересующие вас модули (вы также можете сделать это в любое время после установки)
    # [<en>] enable the modules you are interested in (you can also do this at any time after installation)
