properties:
  logLevel:
    description: |
      Уровень логирования Deckhouse.
  bundle:
    description: |
      Вариант поставки Deckhouse. Определяет включенные по умолчанию модули.
      - `Default` — рекомендованный набор модулей для работы кластера: мониторинга, контроля авторизации, организации работы сети и других потребностей ([актуальный список](https://github.com/deckhouse/deckhouse/blob/main/modules/values-default.yaml)).
      - `Minimal` — минимально возможная поставка, которая включает единственный модуль (этот).
      - `Managed` — поставка для managed-кластеров от облачных провайдеров, например Google Kubernetes Engine.
  releaseChannel:
    description: |
      Желаемый канал обновлений Deckhouse (Deckhouse переключится на него при появлении такой возможности).

      Порядок возрастания стабильности канала обновлений (от **наименее** стабильного, к **наиболее** стабильному): `Alpha`, `Beta`, `EarlyAccess`, `Stable`, `RockSolid`.
  update:
    description: Настройки режима и окон обновления Deckhouse.
    properties:
      mode:
        description: |
          Режим обновления минорных версий Deckhouse (смена релизов). **Не влияет на обновление patch-версий.**
          - `Auto` (автоматический) — Все обновления применяются автоматически.

            Обновления минорной версии Deckhouse (обновления релизов, например с `v1.26.*` на `v1.27.*`), применяются с учетом заданных окон обновлений, либо (если окна обновлений не заданы) по мере появления обновлений на соответствующем канале обновлений.
          - `Manual` (ручной) — Для смены минорной версии Deckhouse (например с `v1.26.*` на `v1.27.*`), необходимо ручное подтверждение. Для подтверждения обновления необходимо отредактировать [CR `DeckhouseRelease`](https://deckhouse.io/ru/documentation/v1/modules/020-deckhouse/cr.html), который соответствует обновляемой версии, установив поле `approved` в `true`.
      windows:
        description: |
          Список окон обновлений в течение суток.
        items:
          properties:
            from:
              description: |
                Время начала окна обновления (в часовом поясе UTC).

                Должно быть меньше времени окончания окна обновления.
            to:
              description: |
                Время окончания окна обновления (в часовом поясе UTC).

                Должно быть больше времени начала окна обновления.
            days:
              description: Дни недели, в которые применяется окно обновлений.
  nodeSelector:
    description: |
      Структура, аналогичная `spec.nodeSelector` Kubernetes Pod.

      Если ничего не указано или указано `false` — будет [использоваться автоматика](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  tolerations:
    description: |
      Структура, аналогичная  `spec.tolerations` в Kubernetes Pod.

      Если ничего не указано или указано `false` — будет [использоваться автоматика](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
