properties:
  logLevel:
    description: |
      Уровень логирования Deckhouse.
  bundle:
    description: |
      Вариант поставки Deckhouse. Определяет включенные по умолчанию модули:
      - `Default` — рекомендованный набор модулей для работы кластера: мониторинга, контроля авторизации, организации работы сети и других потребностей ([актуальный список](https://github.com/deckhouse/deckhouse/blob/main/modules/values-default.yaml));
      - `Minimal` — минимально возможная поставка, которая включает единственный модуль (этот);
      - `Managed` — поставка для managed-кластеров от облачных провайдеров (например, Google Kubernetes Engine).
  releaseChannel:
    description: |
      Желаемый канал обновлений Deckhouse ([переключение](https://deckhouse.io/ru/documentation/v1/deckhouse-faq.html#%D1%87%D1%82%D0%BE-%D0%BF%D1%80%D0%BE%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%B8%D1%82-%D0%BF%D1%80%D0%B8-%D1%81%D0%BC%D0%B5%D0%BD%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B0-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9) на него произойдёт при появлении такой возможности).

      Порядок возрастания стабильности канала обновлений (от **наименее** стабильного, к **наиболее** стабильному): `Alpha`, `Beta`, `EarlyAccess`, `Stable`, `RockSolid`.
  update:
    description: Настройки режима и окон обновления Deckhouse.
    properties:
      mode:
        description: |
          Режим обновления минорных версий Deckhouse (обновление релиза). **Не влияет на обновление patch-версий (patch-релизов).**
          - `Auto` (автоматический) — все обновления применяются автоматически.

            Обновления минорной версии Deckhouse (обновление релиза, например, с `v1.26.*` на `v1.27.*`) применяются с учетом заданных окон обновлений, либо, если окна обновлений не заданы, по мере появления обновлений на соответствующем канале обновлений;
          - `Manual` (ручной) — для обновления минорной версии Deckhouse в ручном режиме (обновление релиза, например, с `v1.26.*` на `v1.27.*`), необходимо подтверждение.
          
            Для подтверждения обновления, в соответствующем [custom resource `DeckhouseRelease`](https://deckhouse.io/ru/documentation/v1/modules/020-deckhouse/cr.html) необходимо установить поле `approved` в `true`.
      windows:
        description: |
          Список окон обновлений в течение суток.
        items:
          properties:
            from:
              description: |
                Время начала окна обновления (в часовом поясе UTC).

                Должно быть меньше времени окончания окна обновления.
            to:
              description: |
                Время окончания окна обновления (в часовом поясе UTC).

                Должно быть больше времени начала окна обновления.
            days:
              description: Дни недели, в которые применяется окно обновлений.
  nodeSelector:
    description: |
      Структура, аналогичная `spec.nodeSelector` Kubernetes Pod.

      Если ничего не указано или указано `false` — будет использоваться [автоматическое выделение узлов](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  tolerations:
    description: |
      Структура, аналогичная  `spec.tolerations` в Kubernetes Pod.

      Если ничего не указано или указано `false` — будет использоваться [автоматическое выделение узлов](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
